modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/samolego/Lakotnik/issues"
license = "MIT"

[[mods]]
modId = "lakotnik"
version = "${version}"
displayName = "Lakotnik - Hunger Preview"
displayURL="https://github.com/samolego/Lakotnik"
authors = "samo_lego"
description = '''
Serverside hunger preview mod.
'''
#logoFile = "template_icon.png"

[[dependencies.lakotnik]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lakotnik]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"
